### ISSUE TITLE
File is missing!

### ISSUE THREAD

**Issue by CJPJ007** [IDSIA/novel2graph#1]
There is no file test_embedding.py in Code folder. Please tell something regarding that.

**Comment by mellacsi** [comment]
You are right, sorry!
.README and GUI updated.

**Comment by CJPJ007** [comment]
Thanks but I do not think so they are updated yet.

**Comment by mellacsi** [comment]
https://github.com/IDSIA/novel2graph/blob/master/README.md#Start

**Comment by CJPJ007** [comment]
Thanks again.
